FROM ekidd/rust-musl-builder:1.40.0 AS builder

COPY src            src
COPY .cargo         .cargo
COPY rust-toolchain .
COPY Cargo.toml     .
COPY Cargo.lock     .

RUN cargo build --release && \
      strip /home/rust/src/target/x86_64-unknown-linux-musl/release/gatekeeperd

FROM scratch

COPY --from=builder /home/rust/src/target/x86_64-unknown-linux-musl/release/gatekeeperd /

EXPOSE 1080

ENV RUST_LOG gatekeeper=info

ENTRYPOINT ["/gatekeeperd"]
