FROM ekidd/rust-musl-builder:1.40.0 AS builder

COPY ./src            src
COPY ./.cargo         .cargo
COPY ./Cargo.lock     .
COPY ./Cargo.toml     .
COPY ./rust-toolchain .

RUN cargo build --release && \
      strip /home/rust/src/target/x86_64-unknown-linux-musl/release/gatekeeperd

FROM scratch

COPY --from=builder /home/rust/src/target/x86_64-unknown-linux-musl/release/gatekeeperd /

EXPOSE 1080

ENV RUST_LOG gatekeeper=info

ENTRYPOINT ["/gatekeeperd"]
