FROM rust:1.83.0 AS builder

COPY src            src
COPY rust-toolchain.toml .
COPY Cargo.toml     .
COPY Cargo.lock     .

RUN cargo build --release
RUN strip /target/release/gatekeeperd

FROM rust:1.83.0

COPY --from=builder /target/release/gatekeeperd /

EXPOSE 1080

ENV RUST_LOG gatekeeper=info

ENTRYPOINT ["/gatekeeperd"]
